CREATE DATABASE SHOP
USE SHOP

CREATE TABLE LAPTOP(
ID_Laptop INT PRIMARY KEY NOT NULL identity,
Name VARCHAR (15) NOT NULL,
CPU VARCHAR (15) NOT NULL,
RAM VARCHAR (10) NOT NULL,
StorageDevice VARCHAR (5) NOT NULL,
Screen VARCHAR (15) NOT NULL,
Model VARCHAR (15),
Price FLOAT NOT NULL)

INSERT INTO LAPTOP VALUES ('Acer','Core i3','4 Gb','HDD','15 inches',' ',30.200);
INSERT INTO LAPTOP VALUES ('Lenovo','core i3','4 Gb','HDD','15 inches',' ',31.600); 
INSERT INTO LAPTOP VALUES ('Samsung','core i7', '8 Gb','SSD','15 inches',' ', 70.555);



CREATE TABLE EMPLOYEE(
ID_Employee INT PRIMARY KEY NOT NULL identity,
Name VARCHAR (15) NOT NULL,
Surname VARCHAR (20) NOT NULL,
Adress VARCHAR (50) NOT NULL,
Salary VARCHAR(10) NOT NULL,
Age DATE NOT NULL,
Position VARCHAR (20) NOT NULL)

INSERT INTO EMPLOYEE VALUES ('Henry','Kavil','NEW-YORK street 1',25.500,'1990-05-03','seller');
INSERT INTO EMPLOYEE VALUES ('Nick','Robinson','NEW-YORK street 2',30.650,'1987-08-09','director');
INSERT INTO EMPLOYEE VALUES ('Robert','Dauni','NEW-YORK street 1',28.200,'1985-12-29','sales assistant');



CREATE TABLE CUSTOMER
( ID_Customer INT PRIMARY KEY NOT NULL identity, 
Name VARCHAR (15) NOT NULL,
Surname VARCHAR (20) NOT NULL,
Data DATE NOT NULL)

INSERT INTO CUSTOMER VALUES ('Sara','Morgan','1999-10-12')
INSERT INTO CUSTOMER VALUES ('Ella','Bell','1989-09-28')
INSERT INTO CUSTOMER VALUES('Bella','Cooper','1989-09-29')



CREATE TABLE ORDERR(
ID_Order INT PRIMARY KEY NOT NULL identity ,
ID_Customer INT,
ID_Laptop INT,
ID_Employee INT,
date_of_purchase DATE NOT NULL, 
QUANTITY INT NOT NULL,

CONSTRAINT FK_ID_Customer FOREIGN KEY (ID_Customer) REFERENCES CUSTOMER,
CONSTRAINT FK_ID_Laptop FOREIGN KEY (ID_Laptop) REFERENCES LAPTOP,
CONSTRAINT FK_ID_Employee FOREIGN KEY (ID_Employee) REFERENCES EMPLOYEE)

INSERT INTO ORDERR VALUES('1','1','3','2019-09-28',2)
INSERT INTO ORDERR VALUES('2','3','1','2019-10-16',1)
INSERT INTO ORDERR VALUES('3','1','2','2019-10-17',1)



SELECT * FROM LAPTOP
SELECT * FROM EMPLOYEE
SELECT * FROM CUSTOMER
SELECT * FROM ORDERR