-Select All
SELECT* FROM CITY

-Select By ID
SELECT* FROM CITY WHERE ID = 1661

-Japanese Cities’ Attributes
SELECT* FROM CITY WHERE COUNTRYCODE = 'JPN'

-Japanese Cities’ Names
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN'

-Weather Observation Station 1
SELECT CITY,STATE FROM STATION

-Weather Observation Station 3
SELECT DISTINCT CITY FROM STATION WHERE MOD(ID , 2) = 0

-Weather Observation Station 5
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;

-Weather Observation Station 7
SELECT DISTINCT(CITY) FROM STATION WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE  '%o' 
OR CITY LIKE  '%u' ORDER BY CITY ASC;  

-Higher Than 75 Marks
SELECT NAME FROM  STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME, 3), ID ASC;

-Employee Names
SELECT NAME FROM EMPLOYEE ORDER BY NAME;